# Generated by Django 4.1.5 on 2023-05-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0006_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(default=None, null=True),
        ),
    ]
