# Generated by Django 4.1.5 on 2023-05-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0008_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
