# Generated by Django 4.1.5 on 2023-05-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0010_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github_account',
            field=models.URLField(blank=True, null=True),
        ),
    ]
