# Generated by Django 4.1.5 on 2023-05-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0011_customuser_github_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
