# Generated by Django 4.1.5 on 2023-05-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0012_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(blank=True, choices=[('ru', 'Russian'), ('en', 'English')], max_length=2, null=True),
        ),
    ]
