# Generated by Django 4.1.5 on 2023-06-01 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0013_customuser_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.season')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.serie')),
            ],
        ),
        migrations.CreateModel(
            name='VolumeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not-watched', 'Не просмотрено'), ('watched', 'Просмотрено'), ('to-watch', 'Буду смотреть')], default='not-watched', max_length=20)),
                ('favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.volume')),
            ],
        ),
        migrations.AddField(
            model_name='volume',
            name='users',
            field=models.ManyToManyField(through='auth_user.VolumeStatus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SerieStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not-watched', 'Не просмотрено'), ('watched', 'Просмотрено'), ('to-watch', 'Буду смотреть')], default='not-watched', max_length=20)),
                ('favorite', models.BooleanField(default=False)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.serie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='serie',
            name='users',
            field=models.ManyToManyField(through='auth_user.SerieStatus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SeasonStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not-watched', 'Не просмотрено'), ('watched', 'Просмотрено'), ('to-watch', 'Буду смотреть')], default='not-watched', max_length=20)),
                ('favorite', models.BooleanField(default=False)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='users',
            field=models.ManyToManyField(through='auth_user.SeasonStatus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChapterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not-watched', 'Не просмотрено'), ('watched', 'Просмотрено'), ('to-watch', 'Буду смотреть')], default='not-watched', max_length=20)),
                ('favorite', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='users',
            field=models.ManyToManyField(through='auth_user.ChapterStatus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.volume'),
        ),
    ]
