# Generated by Django 4.1.5 on 2023-06-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0014_chapter_season_serie_volume_volumestatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterstatus',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='chapterstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='season',
            name='users',
        ),
        migrations.RemoveField(
            model_name='seasonstatus',
            name='season',
        ),
        migrations.RemoveField(
            model_name='seasonstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='season',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='users',
        ),
        migrations.RemoveField(
            model_name='seriestatus',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='seriestatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='users',
        ),
        migrations.RemoveField(
            model_name='volumestatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='volumestatus',
            name='volume',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='ChapterStatus',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='SeasonStatus',
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
        migrations.DeleteModel(
            name='SerieStatus',
        ),
        migrations.DeleteModel(
            name='Volume',
        ),
        migrations.DeleteModel(
            name='VolumeStatus',
        ),
    ]
