# Generated by Django 4.1.5 on 2023-06-12 06:29

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0015_remove_chapterstatus_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format=None, keep_meta=True, quality=100, scale=None, size=[512, 512], upload_to='profile_pictures/'),
        ),
    ]
