# Generated by Django 4.1.5 on 2023-06-14 07:12

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0019_customuser_image_tumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_tumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format=None, keep_meta=True, quality=100, scale=None, size=[96, 96], upload_to='profile_thumbnails/'),
        ),
    ]
