# Generated by Django 4.1.5 on 2023-06-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0020_alter_customuser_image_tumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='image_tumbnail',
            new_name='image_thumbnail',
        ),
    ]
