# Generated by Django 4.1.5 on 2023-06-01 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (русский)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (английский)')),
                ('name_jp', models.CharField(max_length=100, verbose_name='Название (японский)')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (русский)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (английский)')),
                ('name_jp', models.CharField(max_length=100, verbose_name='Название (японский)')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (русский)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (английский)')),
                ('name_jp', models.CharField(max_length=100, verbose_name='Название (японский)')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.season')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (русский)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (английский)')),
                ('name_jp', models.CharField(max_length=100, verbose_name='Название (японский)')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.serie')),
            ],
        ),
        migrations.CreateModel(
            name='VolumeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not-watched', 'Не просмотрено'), ('watched', 'Просмотрено'), ('to-watch', 'Буду смотреть')], default='not-watched', max_length=20)),
                ('favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.volume')),
            ],
        ),
        migrations.AddField(
            model_name='volume',
            name='users',
            field=models.ManyToManyField(through='worker.VolumeStatus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SerieStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not-watched', 'Не просмотрено'), ('watched', 'Просмотрено'), ('to-watch', 'Буду смотреть')], default='not-watched', max_length=20)),
                ('favorite', models.BooleanField(default=False)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.serie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='serie',
            name='users',
            field=models.ManyToManyField(through='worker.SerieStatus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SeasonStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not-watched', 'Не просмотрено'), ('watched', 'Просмотрено'), ('to-watch', 'Буду смотреть')], default='not-watched', max_length=20)),
                ('favorite', models.BooleanField(default=False)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='users',
            field=models.ManyToManyField(through='worker.SeasonStatus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChapterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not-watched', 'Не просмотрено'), ('watched', 'Просмотрено'), ('to-watch', 'Буду смотреть')], default='not-watched', max_length=20)),
                ('favorite', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='users',
            field=models.ManyToManyField(through='worker.ChapterStatus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.volume'),
        ),
    ]
