# Generated by Django 4.1.5 on 2023-06-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_chapter_number_season_number_serie_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='serie',
        ),
        migrations.AddField(
            model_name='chapter',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (английский)'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='description_jp',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (японский)'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (русский)'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='image_file_url',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ССылка'),
        ),
        migrations.AddField(
            model_name='season',
            name='anime_release_view_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='chronological_view_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (английский)'),
        ),
        migrations.AddField(
            model_name='season',
            name='description_jp',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (японский)'),
        ),
        migrations.AddField(
            model_name='season',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (русский)'),
        ),
        migrations.AddField(
            model_name='season',
            name='image_file_url',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AddField(
            model_name='season',
            name='ranobe_release_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ССылка'),
        ),
        migrations.AddField(
            model_name='serie',
            name='anime_release_view_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='chronological_view_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (английский)'),
        ),
        migrations.AddField(
            model_name='serie',
            name='description_jp',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (японский)'),
        ),
        migrations.AddField(
            model_name='serie',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (русский)'),
        ),
        migrations.AddField(
            model_name='serie',
            name='image_file_url',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AddField(
            model_name='serie',
            name='ranobe_release_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ССылка'),
        ),
        migrations.AddField(
            model_name='volume',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (английский)'),
        ),
        migrations.AddField(
            model_name='volume',
            name='description_jp',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (японский)'),
        ),
        migrations.AddField(
            model_name='volume',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (русский)'),
        ),
        migrations.AddField(
            model_name='volume',
            name='image_file_url',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AddField(
            model_name='volume',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ССылка'),
        ),
    ]
