# Generated by Django 4.1.5 on 2023-06-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_remove_volume_serie_chapter_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='season',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка'),
        ),
    ]
