# Generated by Django 4.1.5 on 2023-06-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_alter_chapter_url_alter_season_url_alter_serie_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterstatus',
            name='status',
            field=models.CharField(choices=[('not-watched', 'Не просмотрено'), ('watching', 'Смотрю'), ('watched', 'Просмотрено'), ('to-watch', 'Буду смотреть')], default='not-watched', max_length=20),
        ),
        migrations.AlterField(
            model_name='seasonstatus',
            name='status',
            field=models.CharField(choices=[('not-watched', 'Не просмотрено'), ('watching', 'Смотрю'), ('watched', 'Просмотрено'), ('to-watch', 'Буду смотреть')], default='not-watched', max_length=20),
        ),
        migrations.AlterField(
            model_name='seriestatus',
            name='status',
            field=models.CharField(choices=[('not-watched', 'Не просмотрено'), ('watching', 'Смотрю'), ('watched', 'Просмотрено'), ('to-watch', 'Буду смотреть')], default='not-watched', max_length=20),
        ),
        migrations.AlterField(
            model_name='volumestatus',
            name='status',
            field=models.CharField(choices=[('not-watched', 'Не просмотрено'), ('watching', 'Смотрю'), ('watched', 'Просмотрено'), ('to-watch', 'Буду смотреть')], default='not-watched', max_length=20),
        ),
    ]
