# Generated by Django 4.1.5 on 2023-06-12 12:11

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_alter_chapterstatus_status_alter_seasonstatus_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='image_file_url',
        ),
        migrations.RemoveField(
            model_name='season',
            name='image_file_url',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='image_file_url',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='image_file_url',
        ),
        migrations.AddField(
            model_name='chapter',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format=None, keep_meta=True, quality=100, scale=None, size=[512, 512], upload_to='chapter_pictures/'),
        ),
        migrations.AddField(
            model_name='season',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format=None, keep_meta=True, quality=100, scale=None, size=[512, 512], upload_to='season_pictures/'),
        ),
        migrations.AddField(
            model_name='serie',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format=None, keep_meta=True, quality=100, scale=None, size=[512, 512], upload_to='serie_pictures/'),
        ),
        migrations.AddField(
            model_name='volume',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format=None, keep_meta=True, quality=100, scale=None, size=[512, 512], upload_to='volume_pictures/'),
        ),
        migrations.CreateModel(
            name='VolumeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[512, 512], upload_to='volume_pictures/')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='worker.volume')),
            ],
        ),
        migrations.CreateModel(
            name='SerieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[512, 512], upload_to='serie_pictures/')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='worker.serie')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[512, 512], upload_to='season_pictures/')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='worker.season')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[512, 512], upload_to='chapter_pictures/')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='worker.chapter')),
            ],
        ),
    ]
